#!/usr/bin/env bash

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEST_DATA_DIR="$PROJECT_ROOT/test-data"
REPORT_DIR="$PROJECT_ROOT/reports"
REPORT_FILE="$REPORT_DIR/test-results.md"

mkdir -p "$REPORT_DIR"

echo "# Image Analyzer Test Results" > "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "Generated by \`scripts/run-tests.sh\`." >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

test_count=0
passed_count=0

while IFS= read -r -d '' image; do
    test_count=$((test_count + 1))

    filename="$(basename "$image")"

    echo "Testing: $filename"

    output="$(python3 "$PROJECT_ROOT/application/interact.py" "$image")"

    echo "## $filename" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo '```text' >> "$REPORT_FILE"
    echo "$output" >> "$REPORT_FILE"
    echo '```' >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"

    if echo "$output" | grep -q "HTTP status: 200"; then
        passed_count=$((passed_count + 1))
    fi

done < <(
    find "$TEST_DATA_DIR" -maxdepth 1 -type f \
        \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.jfif" \) \
        -print0 | sort -z
)

{
    echo "## Summary"
    echo ""
    echo "- Tests executed: $test_count"
    echo "- HTTP 200 responses: $passed_count"
} >> "$REPORT_FILE"

echo ""
echo "Tests executed: $test_count"
echo "HTTP 200 responses: $passed_count"
echo "Report: $REPORT_FILE"